{% set name = "GPy" %}
{% set version = "1.13.2" %}
{% set sha256 = "a38256b4dda536a5b5e6134a3924b42d454e987ee801fb6fc8b55a922da27920" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<=38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - scipy >=0.16
    - six
  run:
    - python
    - cython
    - paramz >=0.9.6
    - {{ pin_compatible('numpy') }}
    - scipy <1.12.0,>=1.3.0
    - six
    - matplotlib-base <3.9.0

test:
  commands:
    - export MPLBACKEND="AGG"  # [linux and py2k]
    - python -c "import GPy"
    - pip check
  requires:
    - pip

about:
  home: http://github.com/SheffieldML/GPy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The Gaussian Process Toolbox
  doc_url: https://pythonhosted.org/GPy/
  dev_url: https://github.com/SheffieldML/GPy

extra:
  recipe-maintainers:
    - dirmeier
    - thompsonsed
    - jan-janssen
