{% set name = "GPy" %}
{% set version = "1.9.6" %}
{% set sha256 = "f11d649b3320d4cb836d283706754953277c8696977726803ccd3ee1355a94a7" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}    
  host:
    - python <=3.6
    - setuptools    
    - numpy >=1.7
    - scipy >=0.16
    - six
  run:
    - python
    - paramz >=0.9.0
    - {{ pin_compatible('numpy') }}
    - scipy >=0.16
    - six
    - matplotlib

test:
  imports:
    - GPy

about:
  home: http://github.com/SheffieldML/GPy
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: 'The Gaussian Process Toolbox'
  doc_url: https://pythonhosted.org/GPy/
  dev_url: https://github.com/SheffieldML/GPy

extra:
  recipe-maintainers:
    - dirmeier
