{% set name = "GPy" %}
{% set version = "1.7.7" %}
{% set sha256 = "417f6dda98b97d914d141f6c2e63e0775d87aead29ae64350d2ce249738c9aac" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - toolchain
  run:
    - python
    - paramz >=0.7.4
    - numpy >=1.7
    - scipy >=0.16
    - six
    - matplotlib

test:
  imports:
    - GPy

about:
  home: http://github.com/SheffieldML/GPy
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: 'The Gaussian Process Toolbox'
  doc_url: https://gpy.readthedocs.io/
  dev_url: https://github.com/SheffieldML/GPy

extra:
  recipe-maintainers:
    - dirmeier
