travis:
  secure:
    BINSTAR_TOKEN: dgVR1CuTAk0vSCniRx3DtchCi+krTX1QtVyLAtB0OJUixLLCkEpZiyxK9GZAj3KZWGkVrWfzCeLOnx/7kM+3U/Wmk7uB3/RwoVgNqbpoYtbuFCKhyR2POc1xOKBS9o4WuOcnIkZUMLGL0Axb4bvdADQ2ZGMM087I4RuOTFPdIyN+kXz5sL7W7ci9KsUbHeDXIawumDyph38Rl7tx7dZloiu8FhI5MxmOkWM/PH6jpVkRb1KL1Gvm4pWDdFGpb4cB9hVTLie63d7JEuSba/3xpTtWHlf6qosSes6xfhX9jN5nHBBlFBXPXYb7UHSRIXvTir4JPAY98FCR2cL8xVuh2yKXOVkSU1Y8YTz9P6/nXsmskVILwMMY8SSSDFlAIoQAMvNECyt+A/Bhf/Is116daNHLM/TNCeSDW7k8eO5sanNmxCMxSFV1WC+SQlbGSVE1+yOkgiqLGfMrP4Hyzza3XUsHl3kbkkQxyPUUqBNLrcH4pU3mom0yZbzaedRGQ8n6bNNbkbaeqUGPujoBIUgjh+KVkrOP8RorWFNk0XLp6RBKaFylRHpj1EBAJ6pRObszN4zY6loQq9nhxe71ye00i14GAJPUtAJz5p1iQpYIWp/EHfBSYLrjLZy4N/TidGFjhvCnVR0ywR56I5lMZl2FrVUTHOFKOz5zlEG8b4T86uo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
